name: AI PR Review with CAgent

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  cagent-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AI PR Review
        uses: docker/cagent-action@v2.0.0
        with:
          agent: agents/pr-reviewer.yaml  # Built-in secure PR reviewer
          pr-number: ${{ github.event.pull_request.number }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
